import numpy as np

from typing import Any, Dict, List


class WrapperPython:
    def configure(self, params: Dict[str, Any]): ...
    def emplaceAndPop(self, l: List[Datum]) -> None: ...
    def execute(self) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def waitAndEmplace(self, l: List[Datum]) -> None: ...
    def waitAndPop(self, l: List[Datum]) -> bool: ...

class Datum:
    cvOutputData: np.ndarray
    poseKeypoints: np.ndarray

    def __init__(self): ...
